name: Build Test

on:
  push:
    branches:
      - main
      - dev-branch
      - ua-changes

jobs:
  zTube Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run Jest tests
        run: npm test
      - name: Report test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: jest-results.xml